version: '3'

services:

  database:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: adonis_auth
      MYSQL_USER: adonis
      MYSQL_PASSWORD: 123456
    ports:
      - '3306:3306'
    expose:
      - '3306'